import { useMemo, useState } from 'react';
import { ArrowLeft, Check, Copy, Save } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useSession } from '../context/SessionContext';


export default function Settings() {
  const { session, updateSession } = useSession();
  const [savedFeedback, setSavedFeedback] = useState(false);
  const [copied, setCopied] = useState(false);
  const settings = session.settings;
  const obsHash = session.obsHash;
  const update = (patch) => { setSavedFeedback(false); updateSession({ settings: { ...settings, ...patch } }); };
  const obsUrl = useMemo(() => { const params = new URLSearchParams({ color: settings.textColor, bg: settings.transparentBackground ? 'transparent' : settings.backgroundColor, font: settings.fontFamily, size: String(settings.fontSize), label: settings.label, showLabel: String(settings.showLabel), showTarget: String(settings.showTarget), target: String(settings.targetCount) }); return `${location.origin}/obs/${obsHash}?${params}`; }, [settings, obsHash]);
  const saveSettings = () => { updateSession({ settings }); setSavedFeedback(true); setTimeout(() => setSavedFeedback(false), 2200); };
  const copyUrl = async () => { await navigator.clipboard?.writeText(obsUrl); setCopied(true); setTimeout(() => setCopied(false), 1400); };
  return <main className="screen"><div className="settings-page watch-safe"><header className="settings-header"><div><Link to="/" className="back-link"><ArrowLeft size={19} /></Link><div><span className="eyebrow">SESSÃO ÚNICA</span><h1>Configurações</h1></div></div><span className="profile-badge">Sincronizada</span></header><p className="settings-intro">Personalize a detecção e o visual do contador. As alterações ficam disponíveis em todos os dispositivos conectados.</p>
    <section className="settings-card"><div className="section-heading"><span className="section-number">01</span><div><h2>Detecção de disparos</h2><p>Use valores baixos para ignorar movimentos da mão e detectar apenas impactos mais fortes.</p></div></div><label className="range-field"><span><b>Sensibilidade máxima</b><output>{settings.sensitivity}/200</output></span><input type="range" min="1" max="200" value={settings.sensitivity} onChange={(e) => update({ sensitivity: +e.target.value })} /></label><small style={{ color: '#a1a1aa', marginTop: '-.7rem' }}>Quanto menor o valor, menos sensível fica o sensor. Comece em 20–50.</small><label className="range-field"><span><b>Intervalo mínimo</b><output>{(settings.cooldown / 1000).toFixed(1)}s</output></span><input type="range" min="0" max="20000" step="100" value={settings.cooldown} onChange={(e) => update({ cooldown: +e.target.value })} /></label></section>
    <section className="settings-card"><div className="section-heading"><span className="section-number">02</span><div><h2>Aparência do overlay</h2><p>Defina como o contador aparece no OBS.</p></div></div><label>Texto exibido<input value={settings.label} maxLength="32" onChange={(e) => update({ label: e.target.value })} /></label><label className="check-field"><input type="checkbox" checked={settings.showLabel} onChange={(e) => update({ showLabel: e.target.checked })} /><span>Mostrar identificação junto ao número</span></label><label className="check-field"><input type="checkbox" checked={settings.showTarget} onChange={(e) => update({ showTarget: e.target.checked })} /><span>Mostrar meta da sessão no overlay</span></label><label className="range-field"><span><b>Disparos pretendidos</b><output>{settings.targetCount}</output></span><input type="number" min="1" max="10000" value={settings.targetCount} onChange={(e) => update({ targetCount: Math.min(10000, Math.max(1, Number(e.target.value) || 1)) })} /></label><div className="color-grid"><label>Cor do texto<input type="color" value={settings.textColor} onChange={(e) => update({ textColor: e.target.value })} /></label><label>Cor do fundo<input type="color" value={settings.backgroundColor} disabled={settings.transparentBackground} onChange={(e) => update({ backgroundColor: e.target.value })} /></label></div><label className="check-field"><input type="checkbox" checked={settings.transparentBackground} onChange={(e) => update({ transparentBackground: e.target.checked })} /><span>Usar fundo transparente</span></label><label>Fonte<select value={settings.fontFamily} onChange={(e) => update({ fontFamily: e.target.value })}><option value="system-ui">Sistema</option><option value="Arial, sans-serif">Arial</option><option value="Georgia, serif">Georgia</option><option value="monospace">Monospace</option><option value="'Courier New', monospace">Courier New</option></select></label><label className="range-field"><span><b>Tamanho da fonte</b><output>{settings.fontSize}px</output></span><input type="range" min="24" max="240" value={settings.fontSize} onChange={(e) => update({ fontSize: +e.target.value })} /></label></section>
    <section className="settings-card obs-card"><div className="section-heading"><span className="section-number">03</span><div><h2>Conexão com OBS</h2><p>Use este endereço como fonte de navegador.</p></div></div><div className="hash-line"><span>Identificador</span><strong>{obsHash}</strong></div><input className="obs-url" readOnly value={obsUrl} onFocus={(e) => e.target.select()} /><button className="secondary-button" onClick={copyUrl}><Copy size={17} />{copied ? 'Link copiado' : 'Copiar endereço'}</button></section>
    <button className={`save-button ${savedFeedback ? 'is-saved' : ''}`} onClick={saveSettings} aria-live="polite"><span>{savedFeedback ? <Check size={19} /> : <Save size={19} />}</span>{savedFeedback ? 'Configurações salvas' : 'Salvar configurações'}</button>{savedFeedback && <p className="save-status" role="status">Tudo certo. O perfil padrão foi atualizado.</p>}
  </div></main>;
}
